// Exercises previously missing detail refresh, unsubscribe races and shared feed failure/recovery.
const {spawn}=require('node:child_process');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {WebSocket}=require('../../../adapter/node_modules/ws');
const root=path.resolve(__dirname,'../../..'),dir=fs.mkdtempSync('/tmp/doge-gateway-'),state=path.join(dir,'state.json');
const a='a'.repeat(64),b='b'.repeat(64);let control={fail:false,confirmed:false,calls:0,addressNew:false,addressConfirmed:false};fs.writeFileSync(state,JSON.stringify(control));
const code=`const fs=require('fs');const state=${JSON.stringify(state)};const get=()=>JSON.parse(fs.readFileSync(state));const mod=require.resolve('./adapter/dogecoin.cjs');require.cache[mod]={exports:{refreshInterval:100,health:{source:'fixture'},cooldown:()=>0,budget:()=>({}),liveObservedAt:()=>Date.now(),snapshot:async()=>{await new Promise(r=>setTimeout(r,30));if(get().fail)throw Error('controlled outage');return {blocks:[{id:'c'.repeat(64),height:2}],transactions:[{txid:'d'.repeat(64),fee:1000,vsize:200,value:5000}],'mempool-blocks':[{transactionIds:['d'.repeat(64)]}]};},route:async p=>{if(p.startsWith('/api/address/'))return get().addressNew?[{txid:'e'.repeat(64),status:{confirmed:get().addressConfirmed}}]:[];const id=p.split('/').pop();await new Promise(r=>setTimeout(r,id==='a'.repeat(64)?180:5));return {txid:id,status:{confirmed:get().confirmed}}}}};require('./adapter/server.cjs');`;
const child=spawn(process.execPath,['-e',code],{cwd:root,env:{...process.env,PORT:'4459',DOGE_ROUTER_ORIGIN:'https://tx.taxi'},stdio:['ignore','pipe','pipe']});let logs='';child.stderr.on('data',x=>logs+=x);const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{try{
 for(let i=0;i<50;i++){try{if((await fetch('http://127.0.0.1:4459/healthz')).ok)break;}catch{}await wait(30);}
 const x=new WebSocket('ws://127.0.0.1:4459/api/v1/ws'),y=new WebSocket('ws://127.0.0.1:4459/api/v1/ws');const messages=[],other=[];x.on('message',v=>messages.push(JSON.parse(v)));y.on('message',v=>other.push(JSON.parse(v)));await Promise.all([x,y].map(w=>new Promise(r=>w.on('open',r))));
 x.send(JSON.stringify({'track-tx':a}));await wait(20);x.send(JSON.stringify({'track-tx':b}));x.send(JSON.stringify({'track-mempool-block':0}));await wait(250);
 assert(messages.some(m=>m.tx?.txid===b));assert(!messages.some(m=>m.tx?.txid===a));assert(!other.some(m=>m.tx));assert(messages.some(m=>m['projected-block-transactions']?.blockTransactions.length===1));
 control.confirmed=true;fs.writeFileSync(state,JSON.stringify(control));await wait(220);assert(messages.some(m=>m.tx?.status.confirmed));
 const address='D'+'a'.repeat(33);x.send(JSON.stringify({'track-address':address}));await wait(100);control.addressNew=true;fs.writeFileSync(state,JSON.stringify(control));await wait(220);
 assert(messages.some(m=>m['address-transactions']?.some(t=>t.txid==='e'.repeat(64))));assert(!other.some(m=>m['address-transactions']));
 control.addressConfirmed=true;fs.writeFileSync(state,JSON.stringify(control));await wait(220);assert(messages.some(m=>m['block-transactions']?.some(t=>t.txid==='e'.repeat(64)&&t.status.confirmed)));
 const beforeStop=messages.filter(m=>m['address-transactions']).length;x.send(JSON.stringify({'track-address':'stop'}));await wait(220);assert.equal(messages.filter(m=>m['address-transactions']).length,beforeStop);
 control.fail=true;fs.writeFileSync(state,JSON.stringify(control));await wait(200);assert(messages.some(m=>m['provider-freshness']?.state==='stale'));
 control.fail=false;fs.writeFileSync(state,JSON.stringify(control));await wait(220);assert.equal(messages.at(-1)['provider-freshness']?.state==='live'||!!messages.at(-1)['projected-block-transactions'],true);
 x.close();y.close();fs.writeFileSync(path.join(__dirname,'result.json'),JSON.stringify({controlled:true,lateSubscriptionIgnored:true,detailIsolation:true,confirmationRefresh:true,addressScopedUpdates:true,addressConfirmation:true,addressUnsubscribe:true,pendingFrame:true,outageRecovery:true,frames:messages.length,otherFrames:other.length},null,2));console.log('Gateway behavior checks passed');
 }finally{child.kill();} })().catch(e=>{console.error(e,logs);process.exitCode=1;});
